# Generated by Django 3.2.3 on 2021-05-23 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('find_losts', '0001_initial'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostobject',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='lost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foundobject',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='found', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='notify_id',
            field=models.ForeignKey(db_column='notify_id', on_delete=django.db.models.deletion.CASCADE, related_name='reach_candidates_to_who_found', to='notification.notification'),
        ),
        migrations.AddField(
            model_name='matchedperson',
            name='id_lp',
            field=models.OneToOneField(db_column='lost_person_id', on_delete=django.db.models.deletion.CASCADE, related_name='match', to='find_losts.lostobject'),
        ),
        migrations.AddField(
            model_name='matchedperson',
            name='notify_id_fp',
            field=models.ForeignKey(db_column='notify_id_fp', on_delete=django.db.models.deletion.CASCADE, related_name='reach_match_to_who_found', to='notification.notification'),
        ),
        migrations.AddField(
            model_name='matchedperson',
            name='notify_id_lp',
            field=models.ForeignKey(db_column='notify_id_lp', on_delete=django.db.models.deletion.CASCADE, related_name='reach_match_to_who_lost', to='notification.notification'),
        ),
        migrations.AddField(
            model_name='lostperson',
            name='person_image',
            field=models.ManyToManyField(db_column='images', related_name='images', to='find_losts.LostPersonImage'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='id_fi',
            field=models.ForeignKey(db_column='found_item_id', on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='find_losts.founditem'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='id_li',
            field=models.ForeignKey(db_column='lost_item_id', on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='find_losts.lostitem'),
        ),
        migrations.CreateModel(
            name='FoundPersonImage',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='find_losts.foundperson')),
                ('image', models.ImageField(unique=True, upload_to='')),
            ],
            options={
                'db_table': 'found_person_image',
                'unique_together': {('id', 'image')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('id_li', 'id_fi')},
        ),
    ]
