# Generated by Django 3.2.3 on 2021-05-23 18:36

from django.db import migrations, models
import find_losts.models


class Migration(migrations.Migration):

    dependencies = [
        ('find_losts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostperson',
            name='person_image',
        ),
        migrations.AddField(
            model_name='lostperson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=find_losts.models.lost_person_images),
        ),
    ]
