# Generated by Django 3.1.7 on 2021-05-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_losts', '0003_auto_20210429_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostobject',
            name='date',
            field=models.DateField(),
        ),
    ]
