# Generated by Django 3.2.3 on 2021-05-24 10:04

from django.db import migrations, models
import find_losts.models


class Migration(migrations.Migration):

    dependencies = [
        ('find_losts', '0003_auto_20210523_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundperson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=find_losts.models.found_person_images),
        ),
    ]
