# Generated by Django 3.1.7 on 2021-05-01 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_losts', '0005_auto_20210501_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundpersonimage',
            name='id',
            field=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='find_losts.foundperson'),
        ),
    ]
