# Generated by Django 3.1.7 on 2021-05-03 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_losts', '0006_auto_20210501_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundobject',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='foundpersonimage',
            name='id',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='find_losts.foundperson'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lostobject',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lostpersonimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lostpersonimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='lostpersonimage',
            unique_together=set(),
        ),
    ]
