# Generated by Django 3.1.7 on 2021-05-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_losts', '0007_auto_20210503_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostpersonimage',
            name='image',
            field=models.ImageField(unique=True, upload_to=''),
        ),
    ]
