# Generated by Django 3.1.7 on 2021-05-03 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_losts', '0010_auto_20210503_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostpersonimage',
            name='id',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='find_losts.lostperson'),
        ),
    ]
