# Generated by Django 3.1.7 on 2021-05-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_losts', '0011_auto_20210503_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostobject',
            name='date',
            field=models.DateField(),
        ),
    ]
