# Generated by Django 3.1.7 on 2021-05-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_losts', '0013_auto_20210514_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='image',
        ),
    ]
