# Generated by Django 3.1.7 on 2021-05-21 23:05

from django.db import migrations, models
import find_losts.models


class Migration(migrations.Migration):

    dependencies = [
        ('find_losts', '0014_remove_founditem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=find_losts.models.lost_item_image),
        ),
    ]
