# Generated by Django 3.1.7 on 2021-05-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20210503_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
